{
  "formatVersion": "1.1",
  "component": {
    "group": "able.endpoint.android",
    "module": "able",
    "version": "3.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "prodArpiVolleyVariantProdArpiVolleyApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "able-3.9.1.aar",
          "url": "able-3.9.1.aar",
          "size": 179014,
          "sha512": "099fcfe089a878678c1d43461874b271f96047dcc45114068e5c35683fe36d6ea6a5bc359889e4dc19fe37b51ef439020eb135d4a3656813e2bf0f3c12ec6617",
          "sha256": "0404ce48e06f5763507e452feb11db8e756f72db1388c6261b5690e16ca6ac03",
          "sha1": "a781297b10188088d7cbff5ca5deffb8e70e23a1",
          "md5": "9ca62a575b592aa9da648f6918a54021"
        }
      ]
    },
    {
      "name": "prodArpiVolleyVariantProdArpiVolleyRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "21.1.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "able-3.9.1.aar",
          "url": "able-3.9.1.aar",
          "size": 179014,
          "sha512": "099fcfe089a878678c1d43461874b271f96047dcc45114068e5c35683fe36d6ea6a5bc359889e4dc19fe37b51ef439020eb135d4a3656813e2bf0f3c12ec6617",
          "sha256": "0404ce48e06f5763507e452feb11db8e756f72db1388c6261b5690e16ca6ac03",
          "sha1": "a781297b10188088d7cbff5ca5deffb8e70e23a1",
          "md5": "9ca62a575b592aa9da648f6918a54021"
        }
      ]
    }
  ]
}
