{
  "formatVersion": "1.1",
  "component": {
    "group": "able.endpoint.android",
    "module": "able",
    "version": "3.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "prodArpiVolleyVariantProdArpiVolleyApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "able-3.9.2.aar",
          "url": "able-3.9.2.aar",
          "size": 176225,
          "sha512": "1e08cb13396e596a4d4cb665d3b3afbaa2b32aaeef8d48d0c89508e3d0d271deff6c40813caa53a3737b36ada0ad3f3a64086d1bc34f8ba50a95cead7d651bef",
          "sha256": "6f414acdd8636a2978d2a8677e27c38c66a949f00ae160481a517f4b77484c56",
          "sha1": "1f1c6e9c0dc3eb4d06cff194ae6b51e3445a39e0",
          "md5": "62a902eee66540de884bc10531003ca3"
        }
      ]
    },
    {
      "name": "prodArpiVolleyVariantProdArpiVolleyRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core",
          "version": {
            "requires": "21.1.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "able-3.9.2.aar",
          "url": "able-3.9.2.aar",
          "size": 176225,
          "sha512": "1e08cb13396e596a4d4cb665d3b3afbaa2b32aaeef8d48d0c89508e3d0d271deff6c40813caa53a3737b36ada0ad3f3a64086d1bc34f8ba50a95cead7d651bef",
          "sha256": "6f414acdd8636a2978d2a8677e27c38c66a949f00ae160481a517f4b77484c56",
          "sha1": "1f1c6e9c0dc3eb4d06cff194ae6b51e3445a39e0",
          "md5": "62a902eee66540de884bc10531003ca3"
        }
      ]
    }
  ]
}
